CREATE TABLE IGLA_RUN_PROGRAMS_LOG 
(
  INSTANCE NUMBER 
, SID NUMBER 
, SCHEMA VARCHAR2(50 BYTE) 
, PROGRAM_NAME VARCHAR2(500 BYTE) 
, PROGRAM_TYPE VARCHAR2(40 BYTE) 
, INFO VARCHAR2(4000 BYTE) 
, ADITIONAL_INFO VARCHAR2(200 BYTE) 
, TASK_ID NUMBER 
, SERIAL# NUMBER 
, ACTION VARCHAR2(20 BYTE) 
, DATE_RUN_LOG DATE NOT NULL 
, DATE_END_LOG DATE 
) 

CREATE UNIQUE INDEX IGLA_RUN_PROGRAMS_LOG_INDEX1 ON IGLA_RUN_PROGRAMS_LOG (SCHEMA ASC, PROGRAM_NAME ASC, SID ASC);
